# Generated by Django 5.2.1 on 2025-12-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('contact_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=90)),
            ],
        ),
    ]
