# Generated by Django 5.2.1 on 2025-12-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
